name: Jekyll Bilingual CI/CD

on:
  push:
    branches: [ "main" ]
  schedule:
    # Weekly build to catch dependency updates
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Cache Jekyll gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install

      - name: Build (English)
        run: bundle exec jekyll build --config _config.yml --destination ./_site/en --locale en

      - name: Build (Spanish)
        run: bundle exec jekyll build --config _config.yml --destination ./_site/es --locale es

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
          enable_jekyll: true

      - name: Post-Deploy Cleanup
        run: |
          rm -rf _site
